### ISSUE TITLE
Add logos

### ISSUE THREAD

**Issue by jcbwlkr** [devict/hacktoberfest#1]
We should add logos of participating organizations
- devICT
- Ennovar
- The Labor Party
- MakeICT
- Open Wichita
- Start Up Wichita

**Comment by cjanzen** [comment]
@jcbwlkr Did you have a location in mind, and do we have them already formatted from some other use (is that last part maybe a Barry question)?

**Comment by jcbwlkr** [comment]
I don't really have anything specific in mind and no I don't have the files to use. It just seems like a good idea :)

**Comment by KatherineMichel** [comment]
I submitted pull request #10 to hopefully resolve this.

**Comment by cjanzen** [comment]
Yay @KatherineMichel! Now I don't feel guilty anymore that I went out of town and couldn't do it. :)

**Comment by KatherineMichel** [comment]
No need to feel guilty at all. It gave me my fourth devICT pull request. Woohoo, it's live. https://devict-hacktoberfest.herokuapp.com/
