### ISSUE TITLE
Support org logos that are PNG files

### ISSUE THREAD

**Issue by sethetter** [devict/hacktoberfest#103]
Currently if we have an org in the [org list](https://github.com/devict/hacktoberfest/blob/b049daf753ad5abf307761fccd4f8769777019db/main.go#L104), we expect there to be an SVG logo in `public/images/logos/` with a name matching the org name in the list.

I can't find an SVG for [lake-afton-public-observatory](https://lakeafton.com), so adding png support would be cool :)

**Comment by sethetter** [comment]
@Aatmaj-Zephyr sorry! We are running a local hacktoberfest event in our city and are reserving these issues for members of our community.

**Comment by Aatmaj-Zephyr** [comment]
sure
