### ISSUE TITLE
Fix list styling

### ISSUE THREAD

**Issue by jcbwlkr** [devict/hacktoberfest#11]
There are a few places on the home page where we have unordered lists of text. They look weird because the bullets are way off on the left. Find something that looks better

**Comment by paul-baranowski** [comment]
Can you give me an example of a where this issue happens?

**Comment by jcbwlkr** [comment]
The three bullet points at the bottom of this image

<img width="966" alt="screen shot 2017-09-28 at 10 08 10 am" src="https://user-images.githubusercontent.com/2027263/30974355-13a8325e-a435-11e7-9b53-4da5b4e55b7d.png">

**Comment by paul-baranowski** [comment]
@jcbwlkr Cool, I can take a stab at this.

**Comment by jcbwlkr** [comment]
@paul-baranowski thanks for reaching out, man. In the process of working on other things I believe this issue will be resolved in PR #19 so I'm going to close this one
