### ISSUE TITLE
Question: Is devICT really taking part in Hacktoberfest 2023 ?

### ISSUE THREAD

**Issue by HeetVekariya** [devict/hacktoberfest#112]
- While surfing on net, i found : https://hacktoberfest.devict.org/
 - I visited all the repo's (https://hacktoberfest.devict.org/profile) under this contest/fest 
 - I see that non of all the repo's are active
 - So is it ongoing or not ?

**Comment by sethetter** [comment]
Yes, we are, but we are primarily running our own local Hacktoberfest event for community members in our region.
