### ISSUE TITLE
Integrate with github issues

### ISSUE THREAD

**Issue by jcbwlkr** [devict/hacktoberfest#15]
Add an api endpoint `/api/issues` that hits github for open issues in all of our target orgs and projects then shows it to the user. 
Only show open issues with the tag "hacktoberfest".
This should be on the profile page so we can use their token.
Look at the available information and decide what fields are appropriate to show the user. We might want to make additional calls to get information about each project.
The code in `prs.go` and `profile.js` should be a good starting point.

**Comment by dnguy078** [comment]
I can attempt this in upcoming days.

**Comment by samanthakem** [comment]
@jcbwlkr I submitted a pull request for this issue. See https://github.com/devict/hacktoberfest/pull/20 

Let me know what you think.
