### ISSUE TITLE
Improve github issue styling

### ISSUE THREAD

**Issue by jcbwlkr** [devict/hacktoberfest#22]
I want the table of issues to look pretty much just like https://datatables.net/examples/styling/bootstrap4.html

Specifically the `Show [10] entries`, the search, the pagination, and the `Showing 1 to 10 of 57 entries`

I have already pulled in `https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap4.min.css` which I thought would be sufficient but it's not enough.

**Comment by samanthakem** [comment]
I will see what I can do, changes have to made using the DataTable default css, I see that there are tags such as ul.pagination which might be the focus here.

**Comment by jcbwlkr** [comment]
This was fixed with #31
