### ISSUE TITLE
Show labels on issue list

### ISSUE THREAD

**Issue by kentonh** [devict/hacktoberfest#23]

**Comment by jcbwlkr** [comment]
The search API returns this for issues

```"labels": [
        {
          "url": "https://api.github.com/repos/batterseapower/pinyin-toolkit/labels/bug",
          "name": "bug",
          "color": "ff0000"
        }
      ],```

We could easily enough pass those along to the front end. I would simplify it a bit

In issues.go on `type Issue` add this
```
Labels map[string]string
```

And populate it with the label name as the key and the color as the value like `"bug": "ff0000"`. Then in profile.js loop through the labels and create [badges](https://v4-alpha.getbootstrap.com/components/badge/) to stick on the issue titles.

**Comment by jcbwlkr** [comment]
HOWEVER since we only show issues in the first place if they have `help wanted` or `hacktoberfest` on them maybe we exclude those values? It would just be pretty repetitive otherwise and useful things like `good for newbies` or `bug` would be crowded out

**Comment by aaronarduino** [comment]
@jcbwlkr Would it be helpful to put the labels on a newline to save space?

**Comment by jcbwlkr** [comment]
@aaronarduino yeah that might look good. We should just try it and see
