### ISSUE TITLE
File an issue link not working

### ISSUE THREAD

**Issue by cjanzen** [devict/hacktoberfest#3]
A verrrry clever ploy... :)

From https://devict-hacktoberfest.herokuapp.com, the What projects qualify > File an issue link goes to this URL, which doesn't work: https://devict-hacktoberfest.herokuapp.com/%3Ehttps:/github.com/devict/hacktoberfest/issues/new

**Comment by kentonh** [comment]
This appears to be fixed

**Comment by cjanzen** [comment]
Yup, was fixed by me. :) Am I supposed to close issues I fix or isn't that something the maintainer does?
