### ISSUE TITLE
Unable to log-in

### ISSUE THREAD

**Issue by justyntemme** [devict/hacktoberfest#38]
Both https://devict-hacktoberfest.herokuapp.com/ as well as the docker-compose build report an error after repeatedly making request to the account. 

- secret.env  file is created
- Error on webpage `This application has made an unusually high number of requests to access your account. Please reauthorize the application to continue.`
- Error from terminal (Docker container) `web_1  | 2017/10/15 06:42:40 auth.go:54: securecookie: the value is too long`

**Comment by KatherineMichel** [comment]
I have this problem as well. 
![screen shot 2017-10-15 at 7 18 31 pm](https://user-images.githubusercontent.com/4193054/31590866-be93b1c4-b1dd-11e7-95fe-c20b6a0293bf.png)

**Comment by jcbwlkr** [comment]
This is fixed in b389268009f690de7fe40abb6aad4de93522a46f
