### ISSUE TITLE
Improve devICT hacktoberfest banner

### ISSUE THREAD

**Issue by southekal** [devict/hacktoberfest#54]
- visit [devICT hacktoberfest website!](https://devict-hacktoberfest.herokuapp.com)
- the devICT hacktoberfest banner could do with some ❤️ 

![current hacktoberfest banner](https://devict-hacktoberfest.herokuapp.com/public/images/hacktoberfest-2019.png)

note - keeping it year agnostic would be nice, in case we want to reuse the banner for the upcoming years

**Comment by nessalc** [comment]
Maybe this should be closed? The 2020 site has less of the garish orange and the "2020" _is_ text now.

**Comment by Abubakrce19** [comment]
please assign me

**Comment by outlivo** [comment]
Is this issue open to be worked on?
