### ISSUE TITLE
Make defining number of qualifying commits/gifts flexible

### ISSUE THREAD

**Issue by southekal** [devict/hacktoberfest#55]
Background: 
- for the 2019 devICT hacktoberfest event, we changed the number of qualifying commits to be eligible for a devICT sponsored gift from 4 to 2. We also changed the gift from a tee shirt to a set of stickers for 2019.

Problem:
- Visit [devICT hacktoberfest website!](https://devict-hacktoberfest.herokuapp.com)
- Observe that there are several areas across the website where we mention the number of qualifying commits and gifts.
  - note: this also includes areas such as `meta description`, `twitter:description`
- This makes it hard to identify all areas across templates that needs to be updated if we change the nature of qualifying commits/prizes offered.

Probable Solution:
- Eg: create a `md`/`json` file from where the data can be read.
- Create the data once and use everywhere else 🎉

**Comment by M-ZubairAhmed** [comment]
Hi @southekal can i work on this, i have a little familiarity with go

**Comment by southekal** [comment]
@M-ZubairAhmed - for sure, go for it

**Comment by tiannahenrylewis** [comment]
@southekal if this is still open I would like to give it a try.

**Comment by chrisl8** [comment]
@tiannahenrylewis The wider [Hacktoberfest](https://hacktoberfest.digitalocean.com/) is definitely happening, but that is not related to us.

I'm not sure that we have the volunteers available to run our own devICT hacktoberfest. If we do, one of them will surely respond here soon.

**Comment by sethetter** [comment]
@tiannahenrylewis to expand on what @chrisl8 said, this would still qualify as a hacktoberfest contribution! devICT is just not running it's own Hacktoberfest event this year unfortunately. Feel free to submit a PR for this and we'll still review it 😄

**Comment by cjprieb** [comment]
I'm taking a look at adding this.

**Comment by sethetter** [comment]
Closed with #90 !
