### ISSUE TITLE
Pull back open issues from repos whose status is active/true

### ISSUE THREAD

**Issue by southekal** [devict/hacktoberfest#59]
Problem:
- When you look for `Open Issues`, you will find that issues brought back includes `orgs` and `projects`who have been set to `False` in the Go map hash defined in `main.go`.

![Example of a org/project set to False](https://user-images.githubusercontent.com/540716/66146203-f00fbe80-e5d1-11e9-9a92-b006f02e3d33.png)

Fix:
- We only want to display `Open Issues` from `orgs` and `projects` who have a status `True`

**Comment by M-ZubairAhmed** [comment]
please take a look at the pr https://github.com/devict/hacktoberfest/pull/62
