### ISSUE TITLE
Update checkPRs to count 2 commits as valid

### ISSUE THREAD

**Issue by southekal** [devict/hacktoberfest#60]
Background:

- devICT's 2019 hacktoberfest requires 2 qualifying commits to be eligible for a set of stickers (requirement is different from the previous year where 4 commits were needed). 

Issue:

- the [checkPRs js method!](https://github.com/devict/hacktoberfest/blob/5c783c9368778de46fef6785c9d21771941be7ae/public/js/profile.js#L63) is looking for 4 valid commits instead of 2.

Fix:

- update the javascript to count 2 commits as valid instead of 4

**Comment by M-ZubairAhmed** [comment]
Please take a look at https://github.com/devict/hacktoberfest/pull/61
