### ISSUE TITLE
GitHub action for deploy notifications

### ISSUE THREAD

**Issue by sethetter** [devict/hacktoberfest#82]
reference [the job board](https://github.com/devict/job-board/blob/main/.github/workflows/main.yml) as an example

**Comment by Smartmind12** [comment]
@sethetter Please assign me this issue as i would like to work on it. 
Also kindly label the issue as "Hacktoberfest" for Hacktoberfest 2022.

**Comment by Smartmind12** [comment]
https://github.com/devict/job-board/pull/33

**Comment by sethetter** [comment]
@Smartmind12 sorry, this implementation is incorrect. The issue is for implementing slack deploy notifications on this repo, not the job board. It's already set up on the job board.

Also -- I plan to leave most of the issues around hacktoberfest for people local to our community. I would recommend checking that we don't have other plans for the issue before going ahead and implementing in the future.
