### ISSUE TITLE
Unable to Sign in with GitHub

### ISSUE THREAD

**Issue by peb-peb** [devict/hacktoberfest#94]
Upon pressing the `Sign in with GitHub` button, `could not find a matching session for this request` error is given

<img width="1849" alt="devICT auth error" src="https://user-images.githubusercontent.com/77539004/196019359-057c1fee-69f1-480d-85ee-160d92fb04f6.png">

**Comment by sethetter** [comment]
Wrong url! hacktoberfest.devict.org is what you want
